import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, MinLength } from 'class-validator';

export class ResetPasswordDto {
  @ApiProperty({
    example: 'paste-reset-token-here',
    description: 'Reset token generated by forgot-password',
  })
  @IsNotEmpty()
  token: string;

  @ApiProperty({
    example: 'NewAdmin123!',
    minLength: 8,
    description: 'New password',
  })
  @MinLength(8)
  newPassword: string;
}
